spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jhmarryme/config-repo.git # 注意SSH链接地址
          ignore-local-ssh-settings: true # 重要！忽略本地ssh配置，使用下面密钥。方便移植（如：容器部署）
          # 现在的github默认分支为main
          default-label: main
          force-pull: true # 强制拉取资源文件
          #          # 指定寻找的路径
          #          search-paths:
          #          username:
          #          password:
          private-key: |
                      -----BEGIN EC PRIVATE KEY-----
                      MHcCAQEEILbCLGlR3KNMcpZwEpWVYtTasRsByjDUiekYVR+4AN2DoAoGCCqGSM49
                      AwEHoUQDQgAEkT2YujuJkurVnvm0GFtHbo0Z4ETBoZHsffn+WisdCPlIAtrGc1IA
                      TjAEctyxCEajHw0ATODlGQIVgOTDmQQ/+g==
                      -----END EC PRIVATE KEY-----
          search-paths: "architect/foodie/{application}"

server:
  port: 40009