spring.mail.host=imap.qq.com
spring.mail.port=993
spring.mail.protocol=imap
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}