package com.example.xademo.db2.model;

public class ExternalAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column externalAccount.id
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column externalAccount.amount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    private Long amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column externalAccount.id
     *
     * @return the value of externalAccount.id
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column externalAccount.id
     *
     * @param id the value for externalAccount.id
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column externalAccount.amount
     *
     * @return the value of externalAccount.amount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column externalAccount.amount
     *
     * @param amount the value for externalAccount.amount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }
}