server:
  port: 8002
spring:
  #### kafka配置消费者 start ####
  kafka:
    # 指定kafka server的地址，集群配多个，中间，逗号隔开
#    bootstrap-servers: 1.14.140.53:30072
    bootstrap-servers: 127.0.0.1:9092
    listener:
      # manual: 配置监听手动提交 ack
      # manual_immediate: 手动提交 ack ,消费一条数据完后，立即提交
      ack-mode: manual
      concurrency: 5
    consumer:
      # ack 机制：消费者在消费完消息之后，如何做 ack
      ## 生产中一般不会使用自动确认，使用手动确认，在消息失败时，还能做一些重试等策略
      # enable.auto.commit:true --> 设置自动提交offset
      enable-auto-commit: false

      # 指定默认消费者group id --> 由于在kafka中，同一组中的consumer不会读取到同一个消息，依靠groud.id设置组名
      #      group-id: test
      # 如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      #      auto-commit-interval: 1000

      # 消费者在读取一个没有偏移量的分区或则偏移量无效的情况下如何处理
      ## latest (默认值)：在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      ## earliest：在偏移量无效的情况下，消费者将从起始位置读取分区记录
      auto-offset-reset: earliest

      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #### kafka配置消费者 end ####