spring:
  application:
    name: eureka-server-peer1

server:
  port: 20001

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      # 配置其他Eureka服务的地址
      defaultZone: http://peer2:20002/eureka