server.port=8081

spring.security.oauth2.client.registration.google.client-id=368238083842-3d4gc7p54rs6bponn0qhn4nmf6apf24a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=2RM2QkEaf3A8-iCNqSfdG8wP

spring.security.oauth2.client.registration.github.client-id=c7cb967d0dc02fe90114
spring.security.oauth2.client.registration.github.client-secret=27d671c1873ce6c3dc0d61809dff050202f1d577