package com.example.localmsgtable.db1.model;

public class PaymentMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_msg.id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_msg.order_id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_msg.status
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_msg.try_count
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    private Integer tryCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_msg.id
     *
     * @return the value of payment_msg.id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_msg.id
     *
     * @param id the value for payment_msg.id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_msg.order_id
     *
     * @return the value of payment_msg.order_id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_msg.order_id
     *
     * @param orderId the value for payment_msg.order_id
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_msg.status
     *
     * @return the value of payment_msg.status
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_msg.status
     *
     * @param status the value for payment_msg.status
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_msg.try_count
     *
     * @return the value of payment_msg.try_count
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public Integer getTryCount() {
        return tryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_msg.try_count
     *
     * @param tryCount the value for payment_msg.try_count
     *
     * @mbg.generated Mon Nov 15 10:32:26 CST 2021
     */
    public void setTryCount(Integer tryCount) {
        this.tryCount = tryCount;
    }
}