package com.example.shardingjdbc.model;

import lombok.Builder;

import java.math.BigDecimal;

@Builder
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.total_amount
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_status
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.user_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_id
     *
     * @return the value of t_order_1.order_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_id
     *
     * @param orderId the value for t_order_1.order_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.total_amount
     *
     * @return the value of t_order_1.total_amount
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.total_amount
     *
     * @param totalAmount the value for t_order_1.total_amount
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_status
     *
     * @return the value of t_order_1.order_status
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_status
     *
     * @param orderStatus the value for t_order_1.order_status
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.user_id
     *
     * @return the value of t_order_1.user_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.user_id
     *
     * @param userId the value for t_order_1.user_id
     *
     * @mbg.generated Mon Nov 08 17:51:41 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}