spring:
  application:
    name: stream-server
  rabbitmq:
    host: 1.14.140.53
    port: 30050
    username: jhmarryme
    password: 541224
  cloud:
    stream:
      bindings:
        myTopic-consumer:
          destination: myTopic
        myTopic-producer:
          destination: myTopic
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 40020
