spring:
  application:
    name: stream-server
  rabbitmq:
    host: 1.14.140.53
    port: 30050
    username: jhmarryme
    password: 541224
  cloud:
    stream:
      bindings:
        # 绑定Channel到broadcast
        myTopic-consumer:
          destination: broadcast
        myTopic-producer:
          destination: broadcast
        # 消息分组示例
        group-consumer:
          destination: group-topic
          group: group-a
          consumer:
            # 打开消费者的消费分区功能
            partitioned: true
        group-producer:
          destination: group-topic
          producer:
            # 两个消息分区
            partitionCount: 4
            # SpEL (Key resolver) 可以定义复杂表达式生成Key 这里用最简化的配置，只有索引参数为1的节点（消费者），才能消费消息
            partition-key-expression: '1'
        delayed-consumer:
          destination: delayed-topic
        delayed-producer:
          destination: delayed-topic
        error-consumer:
          destination: error-topic
          consumer:
            max-attempts: 1
        error-producer:
          destination: error-topic
      # 当前消费者实例总数
      instance-count: 2
      # 最大值instanceCount-1，当前实例的索引号
      instance-index: 1
      rabbit:
        bindings:
          delayed-consumer:
            consumer:
              # 延迟消息配置
              delayed-exchange: true
          delayed-producer:
            producer:
              # 延迟消息配置
              delayed-exchange: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 40020
