spring:
  application:
    name: stream-server
  rabbitmq:
    host: 1.14.140.53
    port: 30050
    username: jhmarryme
    password: 541224
  cloud:
    stream:
      bindings:
        # 绑定Channel到broadcast
        myTopic-consumer:
          destination: broadcast
        myTopic-producer:
          destination: broadcast
        # 消息分组示例
        group-consumer:
          destination: group-topic
          group: group-b
        group-producer:
          destination: group-topic
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 40020
