package com.example.shardingjdbc.dao;

import com.example.shardingjdbc.model.Order;
import com.example.shardingjdbc.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_1
     *
     * @mbg.generated Thu Nov 04 15:08:44 CST 2021
     */
    int updateByPrimaryKey(Order record);
}