---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jhmarryme.
--- DateTime: 2021/11/19 下午12:39
---
-- 模拟限流

-- 用作限流的Key
local key = "your key"

-- 限流的最大阈值=2
local limit = 2

-- 当前流量大小
local currentLimit = 2

-- 是否超出限流标准
if currentLimit + 1 > limit then
    print("reject")
    return false
else
    print("accept")
    return true
end