---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jhmarryme.
--- DateTime: 2021/11/24 上午9:35
---

-- 获取方法签名key
local methodKey = KEYS[1]
redis.log(redis.LOG_DEBUG, "key is ", methodKey)

-- 调用时传入的限流大小
local limit = tonumber(ARGV[1])

-- 获取当前流量大小
local count = tonumber(redis.call('get', methodKey) or "0")

-- 限流逻辑
if count + 1 > limit then
    -- 拒绝
    return false
else
    -- 没有超过阈值
    -- 设置当前访问数量 + 1
    redis.call("INCRBY", methodKey, 1)
    -- 设置过期时间
    redis.call("EXPIRE", methodKey, 1)
    -- 允许
    return true
end
