package com.example.xademo.db2.dao;

import com.example.xademo.db2.model.ExternalAccount;
import com.example.xademo.db2.model.ExternalAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExternalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    long countByExample(ExternalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int deleteByExample(ExternalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int insert(ExternalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int insertSelective(ExternalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    List<ExternalAccount> selectByExample(ExternalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    ExternalAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") ExternalAccount record, @Param("example") ExternalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int updateByExample(@Param("record") ExternalAccount record, @Param("example") ExternalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int updateByPrimaryKeySelective(ExternalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table externalAccount
     *
     * @mbg.generated Thu Nov 11 11:08:26 CST 2021
     */
    int updateByPrimaryKey(ExternalAccount record);
}